---
# tasks file for run_helm_chart

- name: Update Helm chart repository
  become: yes
  shell: helm repo update

- name: Kubeconfig
  become: yes
  shell: export KUBECONFIG=/home/ubuntu/.kube/config 

- name: Add helm repo
  become_user: ubuntu
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"
- name: Install Mysql Chart
  become_user: ubuntu
  kubernetes.core.helm:
    name: mysql
    namespace: default
    chart_ref: bitnami/mysql
    values:
      primary:
        persistence:
          enabled: false