---
# tasks file for deploy-k8s 
# only used by master node

- name: Install kubectl on the master node
  become: yes
  apt:
    name: kubectl
    state: present
    update_cache: yes
    force: yes

- name: Create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: 0755

- name: Initialize the kubernetes cluster on the master node
  become: yes
  shell: sudo kubeadm init --control-plane-endpoint {{ groups['Master'][0] }}:6443 --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem


- name: Configure users cluster access
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
 
- name: Install Pod network(Flannel)
  become: yes
  shell: export KUBECONFIG=/home/ubuntu/.kube/config && kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Get join command from the master node
  shell: kubeadm token create --print-join-command
  register: join_command
  
- name: Set join command
  set_fact:
    join_command:  "{{ join_command.stdout_lines[0] }}"
  